import type { EquipSlot, ItemDef } from '../types';

export const SLOT_ORDER: EquipSlot[] = ['head', 'body', 'feet', 'weapon', 'horse'];

export const SLOTS: Record<EquipSlot, { name: string; icon: string }> = {
  head: { name: 'Şapka', icon: '🎩' },
  body: { name: 'Giysi', icon: '🧥' },
  feet: { name: 'Çizme', icon: '👢' },
  weapon: { name: 'Silah', icon: '💥' },
  horse: { name: 'Binek', icon: '🐎' },
};

export const ITEM_LIST: ItemDef[] = [
  // Şapkalar
  {
    id: 'straw_hat',
    name: 'Hasır Şapka',
    icon: '👒',
    kind: 'equipment',
    slot: 'head',
    description: 'Güneşi keser, rüzgârda uçar.',
    price: 15,
    value: 6,
    level: 1,
    bonuses: { charm: 1 },
  },
  {
    id: 'felt_hat',
    name: 'Keçe Kovboy Şapkası',
    icon: '🎩',
    kind: 'equipment',
    slot: 'head',
    description: 'Geniş kenarlı, sağlam. Tam bir kovboy şapkası.',
    price: 65,
    value: 26,
    level: 3,
    bonuses: { agility: 1, charm: 1 },
  },
  {
    id: 'sheriff_hat',
    name: 'Şerif Şapkası',
    icon: '🎩',
    kind: 'equipment',
    slot: 'head',
    description: 'Walt Hollis’in yedek şapkası. Taşıyanın sözü dinlenir.',
    value: 150,
    level: 8,
    bonuses: { charm: 2, aim: 2 },
  },
  {
    id: 'bowler_hat',
    name: 'Melon Şapka',
    icon: '🎩',
    kind: 'equipment',
    slot: 'head',
    description: 'Doğulu iş adamlarının gözdesi. Kumar masasında şans getirdiği söylenir.',
    price: 380,
    value: 152,
    level: 8,
    bonuses: { charm: 3, agility: 1 },
  },

  // Giysiler
  {
    id: 'patched_shirt',
    name: 'Yamalı Gömlek',
    icon: '👕',
    kind: 'equipment',
    slot: 'body',
    description: 'Çok yol görmüş. Yamaların yamaları var.',
    price: 12,
    value: 5,
    level: 1,
    bonuses: { strength: 1 },
  },
  {
    id: 'leather_vest',
    name: 'Deri Yelek',
    icon: '🦺',
    kind: 'equipment',
    slot: 'body',
    description: 'Dayanıklı ve rahat. Cepleri de bol.',
    price: 85,
    value: 34,
    level: 3,
    bonuses: { strength: 1, agility: 1 },
  },
  {
    id: 'duster_coat',
    name: 'Toz Paltosu',
    icon: '🧥',
    kind: 'equipment',
    slot: 'body',
    description: 'Uzun, ağır ve rüzgârda dalgalanır. Toz fırtınasına karşı en iyi dostun.',
    price: 320,
    value: 128,
    level: 7,
    bonuses: { agility: 2, strength: 1, aim: 1 },
  },
  {
    id: 'poncho',
    name: 'Meksika Pançosu',
    icon: '🧣',
    kind: 'equipment',
    slot: 'body',
    description: 'Altında ne sakladığını kimse bilemez.',
    price: 540,
    value: 216,
    level: 10,
    bonuses: { aim: 2, charm: 2 },
  },

  // Çizmeler
  {
    id: 'old_boots',
    name: 'Eski Çizme',
    icon: '👢',
    kind: 'equipment',
    slot: 'feet',
    description: 'Tabanı biraz su alıyor ama idare eder.',
    price: 18,
    value: 7,
    level: 1,
    bonuses: { agility: 1 },
  },
  {
    id: 'spur_boots',
    name: 'Mahmuzlu Çizme',
    icon: '👢',
    kind: 'equipment',
    slot: 'feet',
    description: 'Her adımda şıngırdar. Herkes geldiğini duyar.',
    price: 140,
    value: 56,
    level: 4,
    bonuses: { agility: 2, charm: 1 },
  },
  {
    id: 'snakeskin_boots',
    name: 'Yılan Derisi Çizme',
    icon: '👢',
    kind: 'equipment',
    slot: 'feet',
    description: 'Hem şık hem sağlam. Yılanlar bu çizmeden hoşlanmaz.',
    price: 460,
    value: 184,
    level: 9,
    bonuses: { agility: 3, strength: 1 },
  },

  // Silahlar
  {
    id: 'bowie_knife',
    name: 'Av Bıçağı',
    icon: '🔪',
    kind: 'equipment',
    slot: 'weapon',
    description: 'Uzun ve keskin. Yakın mesafede işe yarar.',
    price: 22,
    value: 9,
    level: 1,
    bonuses: { agility: 1 },
    weapon: { min: 3, max: 6 },
  },
  {
    id: 'rusty_pistol',
    name: 'Paslı Tabanca',
    icon: '💥',
    kind: 'equipment',
    slot: 'weapon',
    description: 'Her seferinde ateş almayabilir ama almadığı da pek olmaz.',
    price: 30,
    value: 12,
    level: 1,
    weapon: { min: 4, max: 8 },
  },
  {
    id: 'six_shooter',
    name: 'Altıpatlar',
    icon: '💥',
    kind: 'equipment',
    slot: 'weapon',
    description: 'Batının en sevilen tabancası. Altı kurşun, altı fırsat.',
    price: 160,
    value: 64,
    level: 3,
    bonuses: { aim: 1 },
    weapon: { min: 7, max: 13 },
  },
  {
    id: 'double_barrel',
    name: 'Çifte Kırma',
    icon: '💥',
    kind: 'equipment',
    slot: 'weapon',
    description: 'İsabet etmesi zor, ettiğinde ise affetmez.',
    price: 380,
    value: 152,
    level: 6,
    bonuses: { strength: 1 },
    weapon: { min: 6, max: 24 },
  },
  {
    id: 'hunting_rifle',
    name: 'Av Tüfeği',
    icon: '💥',
    kind: 'equipment',
    slot: 'weapon',
    description: 'Uzun namlu, sağlam dipçik. Ağır ama isabetli.',
    price: 420,
    value: 168,
    level: 6,
    bonuses: { aim: 2, agility: -1 },
    weapon: { min: 10, max: 18 },
  },
  {
    id: 'silver_revolver',
    name: 'Gümüş Kabzalı Revolver',
    icon: '💥',
    kind: 'equipment',
    slot: 'weapon',
    description: 'Yılan Carver’ın gözbebeği. Kabzasında bir çıngıraklı yılan işli.',
    value: 420,
    level: 10,
    bonuses: { aim: 2, charm: 1 },
    weapon: { min: 14, max: 22 },
  },
  {
    id: 'long_rifle',
    name: 'Keskin Nişancı Tüfeği',
    icon: '💥',
    kind: 'equipment',
    slot: 'weapon',
    description: 'Dürbünüyle bir mil öteden sineğin kanadını vurur.',
    price: 1100,
    value: 440,
    level: 12,
    bonuses: { aim: 3, agility: -1 },
    weapon: { min: 16, max: 26 },
  },

  // Binekler
  {
    id: 'old_mule',
    name: 'Yaşlı Katır',
    icon: '🐴',
    kind: 'equipment',
    slot: 'horse',
    description: 'İnatçı ama sadık. Yürümekten iyidir.',
    price: 90,
    value: 36,
    level: 1,
    speed: 1.3,
  },
  {
    id: 'bay_horse',
    name: 'Doru At',
    icon: '🐎',
    kind: 'equipment',
    slot: 'horse',
    description: 'Güçlü ve güvenilir bir çiftlik atı.',
    price: 320,
    value: 128,
    level: 4,
    bonuses: { agility: 1 },
    speed: 1.6,
  },
  {
    id: 'mustang',
    name: 'Mustang',
    icon: '🐎',
    kind: 'equipment',
    slot: 'horse',
    description: 'Ovaların vahşi ruhu. Evcilleştirmesi zor, yakalaması imkânsız.',
    price: 850,
    value: 340,
    level: 8,
    bonuses: { agility: 2 },
    speed: 1.9,
  },
  {
    id: 'arabian',
    name: 'Arap Atı',
    icon: '🐎',
    kind: 'equipment',
    slot: 'horse',
    description: 'Zarif, hızlı ve pahalı. Kasabadaki herkes dönüp bakar.',
    price: 2000,
    value: 800,
    level: 12,
    bonuses: { agility: 2, charm: 2 },
    speed: 2.3,
  },

  // Ganimet
  {
    id: 'rabbit_pelt',
    name: 'Tavşan Postu',
    icon: '🐇',
    kind: 'loot',
    description: 'Yumuşacık. Eldiven yapmak için birebir.',
    value: 6,
    level: 1,
  },
  {
    id: 'fish',
    name: 'Alabalık',
    icon: '🐟',
    kind: 'loot',
    description: 'Taze ve parlak. Otelin aşçısı iyi para verir.',
    value: 4,
    level: 1,
  },
  {
    id: 'cowhide',
    name: 'İnek Derisi',
    icon: '🐮',
    kind: 'loot',
    description: 'Tabakhaneye götürülmeyi bekliyor.',
    value: 9,
    level: 1,
  },
  {
    id: 'deer_antler',
    name: 'Geyik Boynuzu',
    icon: '🦌',
    kind: 'loot',
    description: 'Salonun duvarında çok iyi durur.',
    value: 16,
    level: 1,
  },
  {
    id: 'gold_nugget',
    name: 'Altın Parçası',
    icon: '🪙',
    kind: 'loot',
    description: 'Küçük ama gerçek. Ceviz büyüklüğünde olanı hâlâ bulunmadı.',
    value: 45,
    level: 1,
  },
  {
    id: 'silver_ore',
    name: 'Gümüş Cevheri',
    icon: '🪨',
    kind: 'loot',
    description: 'Parlak damarlarıyla ağır bir taş.',
    value: 22,
    level: 1,
  },
  {
    id: 'wanted_poster',
    name: 'Aranıyor İlanı',
    icon: '📜',
    kind: 'loot',
    description: 'Yırtık bir ilan. Üzerindeki yüz tanıdık geliyor.',
    value: 3,
    level: 1,
  },
  {
    id: 'pocket_watch',
    name: 'Cep Saati',
    icon: '⌚',
    kind: 'loot',
    description: 'Arkasında bir baş harf kazınmış. Birisi onu arıyor olmalı.',
    value: 60,
    level: 1,
  },
];
