import type { JobDef } from '../types';

export const JOB_LIST: JobDef[] = [
  // Coyote Creek
  {
    id: 'sweep_saloon',
    name: 'Salonu süpür',
    icon: '🧹',
    locationId: 'town',
    description: 'Dünkü kavgadan kalan kırık bardakları topla. Kimse sormaz, kimse söylemez.',
    weights: { strength: 1, charm: 1 },
    difficulty: 0,
    money: 2,
    xp: 2,
    danger: 0,
    drops: [],
  },
  {
    id: 'deliver_mail',
    name: 'Posta dağıt',
    icon: '✉️',
    locationId: 'town',
    description: 'Kasabanın mektuplarını sahiplerine ulaştır. Bahçe köpeklerine dikkat.',
    weights: { agility: 1.5, charm: 0.5 },
    difficulty: 2,
    money: 4,
    xp: 3,
    danger: 0.02,
    drops: [],
  },
  {
    id: 'bartend',
    name: 'Barmenlik yap',
    icon: '🍺',
    locationId: 'town',
    description: 'Viski doldur, dedikodu dinle. Kavga çıkarsa tezgâhın arkasına eğil.',
    weights: { charm: 1.5, agility: 0.5 },
    difficulty: 5,
    money: 7,
    xp: 5,
    danger: 0.1,
    drops: [{ itemId: 'felt_hat', chance: 0.01 }],
  },

  // Miller Çiftliği
  {
    id: 'mend_fences',
    name: 'Çit onar',
    icon: '🪵',
    locationId: 'ranch',
    description: 'Kaçan ineklerin çitlerde açtığı delikleri kapat.',
    weights: { strength: 1.5, agility: 0.5 },
    difficulty: 0,
    money: 3,
    xp: 3,
    danger: 0.05,
    drops: [{ itemId: 'straw_hat', chance: 0.02 }],
  },
  {
    id: 'herd_cattle',
    name: 'Sığır güt',
    icon: '🐄',
    locationId: 'ranch',
    description: 'Sürüyü otlaktan ağıla, ağıldan otlağa taşı. Geride kalan olmasın.',
    weights: { agility: 1.5, charm: 0.5 },
    difficulty: 3,
    money: 5,
    xp: 5,
    danger: 0.08,
    drops: [{ itemId: 'cowhide', chance: 0.2 }],
  },
  {
    id: 'break_horses',
    name: 'Yabani at terbiye et',
    icon: '🐎',
    locationId: 'ranch',
    description: 'Eyere alışmamış mustangların sırtında kalmaya çalış.',
    weights: { agility: 1, strength: 1 },
    difficulty: 9,
    money: 10,
    xp: 9,
    danger: 0.22,
    drops: [{ itemId: 'spur_boots', chance: 0.01 }],
  },

  // Çam Ormanı
  {
    id: 'chop_wood',
    name: 'Odun kes',
    icon: '🪓',
    locationId: 'forest',
    description: 'Kasabanın sobaları kış boyu yanacak. Balta senden, çam ağaçları ormandan.',
    weights: { strength: 2 },
    difficulty: 3,
    money: 3,
    xp: 3,
    danger: 0.06,
    drops: [],
  },
  {
    id: 'hunt_rabbits',
    name: 'Tavşan avla',
    icon: '🐇',
    locationId: 'forest',
    description: 'Hızlıdırlar ama meraklıdırlar. Sabırlı ol, iyi nişan al.',
    weights: { aim: 1.5, agility: 0.5 },
    difficulty: 2,
    money: 3,
    xp: 4,
    danger: 0.03,
    drops: [{ itemId: 'rabbit_pelt', chance: 0.35 }],
  },
  {
    id: 'hunt_deer',
    name: 'Geyik avla',
    icon: '🦌',
    locationId: 'forest',
    description: 'Rüzgârı arkana alma, yoksa kokunu alırlar.',
    weights: { aim: 1.5, strength: 0.5 },
    difficulty: 8,
    money: 8,
    xp: 8,
    danger: 0.1,
    drops: [
      { itemId: 'deer_antler', chance: 0.2 },
      { itemId: 'bowie_knife', chance: 0.01 },
    ],
  },

  // Yılan Nehri
  {
    id: 'fish',
    name: 'Balık tut',
    icon: '🎣',
    locationId: 'river',
    description: 'Oltanı at ve bekle. Alabalıklar sabahın erken saatlerinde aç olur.',
    weights: { agility: 1, aim: 1 },
    difficulty: 1,
    money: 2,
    xp: 3,
    danger: 0.01,
    drops: [{ itemId: 'fish', chance: 0.4 }],
  },
  {
    id: 'pan_gold',
    name: 'Altın ayıkla',
    icon: '✨',
    locationId: 'river',
    description: 'Tavaya kum doldur, çalkala, parıltıyı ara. Çoğu zaman sadece kum çıkar.',
    weights: { agility: 1.5, strength: 0.5 },
    difficulty: 4,
    money: 4,
    xp: 5,
    danger: 0.02,
    drops: [{ itemId: 'gold_nugget', chance: 0.12 }],
  },
  {
    id: 'ferry',
    name: 'Sal ile yolcu taşı',
    icon: '🛶',
    locationId: 'river',
    description: 'Yolcuları karşı kıyıya geçir. Sohbeti iyi olanın bahşişi de iyi olur.',
    weights: { strength: 1, charm: 1 },
    difficulty: 3,
    money: 6,
    xp: 4,
    danger: 0.08,
    drops: [],
  },

  // Gümüş Sırtı Madeni
  {
    id: 'mine_silver',
    name: 'Gümüş kaz',
    icon: '⛏️',
    locationId: 'mine',
    description: 'Kazmayı sallamaya devam et. Kanaryan şarkı söylediği sürece sorun yok.',
    weights: { strength: 2 },
    difficulty: 9,
    money: 8,
    xp: 7,
    danger: 0.15,
    drops: [{ itemId: 'silver_ore', chance: 0.2 }],
  },
  {
    id: 'blast_rock',
    name: 'Dinamitle kaya patlat',
    icon: '🧨',
    locationId: 'mine',
    description: 'Fitili yak ve koş. Yeterince hızlı koş.',
    weights: { agility: 1, strength: 1 },
    difficulty: 13,
    money: 14,
    xp: 13,
    danger: 0.3,
    drops: [
      { itemId: 'silver_ore', chance: 0.3 },
      { itemId: 'gold_nugget', chance: 0.05 },
    ],
  },

  // Demiryolu Şantiyesi
  {
    id: 'lay_track',
    name: 'Ray döşe',
    icon: '🛤️',
    locationId: 'railroad',
    description: 'Traversleri diz, rayları çak. Batıya doğru her gün bir mil daha.',
    weights: { strength: 1.5, agility: 0.5 },
    difficulty: 10,
    money: 11,
    xp: 10,
    danger: 0.12,
    drops: [],
  },
  {
    id: 'guard_payroll',
    name: 'Maaş vagonunu koru',
    icon: '💰',
    locationId: 'railroad',
    description: 'İşçilerin maaşı bu vagonda. Haydutlar da bunu biliyor.',
    weights: { aim: 1.5, charm: 0.5 },
    difficulty: 16,
    money: 18,
    xp: 17,
    danger: 0.25,
    drops: [{ itemId: 'pocket_watch', chance: 0.05 }],
  },

  // Kızıl Kanyon
  {
    id: 'track_outlaws',
    name: 'Haydut izi sür',
    icon: '🐾',
    locationId: 'canyon',
    description: 'Taze at izleri, sönmüş kamp ateşleri... Çete buralarda bir yerde.',
    weights: { agility: 1, aim: 1 },
    difficulty: 14,
    money: 16,
    xp: 16,
    danger: 0.3,
    drops: [{ itemId: 'wanted_poster', chance: 0.25 }],
  },
  {
    id: 'watch_smugglers',
    name: 'Kaçakçı yolunu gözetle',
    icon: '🔭',
    locationId: 'canyon',
    description: 'Kayaların arasına saklan ve sınırdan gelen kervanları say.',
    weights: { aim: 1, charm: 1 },
    difficulty: 18,
    money: 20,
    xp: 19,
    danger: 0.2,
    drops: [{ itemId: 'poncho', chance: 0.02 }],
  },
];
