import type { NpcDef } from '../types';

export const NPC_LIST: NpcDef[] = [
  {
    id: 'drunk_cowboy',
    name: 'Sarhoş Kovboy',
    icon: '🥴',
    locationId: 'town',
    description: 'Salonun demirbaşı. Elleri titriyor ama tetiği nerede bulacağını hâlâ biliyor.',
    level: 1,
    hp: 60,
    aim: 1,
    agility: 1,
    weapon: { min: 3, max: 7 },
    moneyMin: 8,
    moneyMax: 15,
    xp: 12,
    drops: [],
  },
  {
    id: 'card_sharp',
    name: 'Hilebaz Kumarbaz',
    icon: '🃏',
    locationId: 'town',
    description: 'Kolunda as, yeleğinde küçük bir tabanca. Kaybetmeyi hiç sevmez.',
    level: 4,
    hp: 100,
    aim: 6,
    agility: 5,
    weapon: { min: 5, max: 10 },
    moneyMin: 25,
    moneyMax: 45,
    xp: 35,
    drops: [{ itemId: 'felt_hat', chance: 0.05 }],
  },
  {
    id: 'bandit_rookie',
    name: 'Acemi Haydut',
    icon: '😤',
    locationId: 'canyon',
    description: 'Çeteye yeni katılmış, kendini kanıtlamak istiyor. Tehlikeli bir kombinasyon.',
    level: 5,
    hp: 130,
    aim: 7,
    agility: 6,
    weapon: { min: 7, max: 12 },
    moneyMin: 40,
    moneyMax: 70,
    xp: 50,
    drops: [{ itemId: 'wanted_poster', chance: 0.3 }],
  },
  {
    id: 'bandit_veteran',
    name: 'Kıdemli Haydut',
    icon: '😠',
    locationId: 'canyon',
    description: 'Yüzü yara izleriyle dolu. Her birinin hikâyesini anlatmaya hazır.',
    level: 8,
    hp: 160,
    aim: 10,
    agility: 8,
    weapon: { min: 10, max: 16 },
    moneyMin: 70,
    moneyMax: 120,
    xp: 90,
    drops: [
      { itemId: 'wanted_poster', chance: 0.4 },
      { itemId: 'duster_coat', chance: 0.04 },
    ],
  },
  {
    id: 'snake_carver',
    name: 'Jed “Yılan” Carver',
    icon: '🐍',
    locationId: 'canyon',
    description: 'Kızıl Kanyon çetesinin elebaşı. Söylentiye göre hiç düello kaybetmemiş.',
    level: 12,
    hp: 250,
    aim: 14,
    agility: 12,
    weapon: { min: 14, max: 22 },
    moneyMin: 250,
    moneyMax: 400,
    xp: 250,
    drops: [{ itemId: 'silver_revolver', chance: 0.5 }],
  },
];
