// Copies the icons the game uses out of @iconify-json/game-icons into
// src/ui/art/glyphs.ts, so the app ships a few dozen icons instead of 4,000.
// Run with `npm run glyphs` after changing the list below.

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const set = require('@iconify-json/game-icons/icons.json');

const NAMES = [
  // Locations
  'saloon', 'barn', 'forest', 'river', 'gold-mine', 'steam-locomotive', 'monument-valley',
  // Jobs
  'broom', 'envelope', 'beer-stein', 'wooden-fence', 'cow', 'horse-head', 'axe-in-stump', 'rabbit', 'deer',
  'fishing-pole', 'gold-nuggets', 'raft', 'mining', 'dynamite', 'rail-road', 'strongbox', 'boot-prints', 'spyglass',
  // Items
  'skimmer-hat', 'western-hat', 'outback-hat', 'top-hat', 'shirt', 'leather-vest', 'pirate-coat', 'poncho',
  'leather-boot', 'cowboy-boot', 'boots', 'bowie-knife', 'revolver', 'sawed-off-shotgun', 'musket',
  'winchester-rifle', 'donkey', 'rabbit-head', 'fishing', 'animal-hide', 'deer-head', 'ore', 'wanted-reward',
  'pocket-watch',
  // People
  'beer-bottle', 'card-ace-spades', 'bandana', 'bandit', 'rattlesnake', 'police-badge', 'miner',
  // Classes and attributes
  'cowboy-holster', 'lasso', 'compass', 'law-star', 'biceps', 'sprint', 'bullseye', 'conversation',
  // Interface
  'two-coins', 'hearts', 'power-lightning', 'round-star', 'bandage-roll', 'hourglass', 'campfire', 'horseshoe',
  'bed', 'shop', 'scroll-unfurled', 'newspaper', 'treasure-map', 'upgrade', 'trophy', 'knocked-out-stars',
  'crossed-pistols', 'bullet-impacts', 'dodge', 'blood', 'swap-bag', 'knapsack', 'cactus', 'tumbleweed',
  'check-mark', 'padlock', 'cancel', 'sunset',
];

const lines = [];
for (const name of NAMES) {
  const icon = set.icons[name];
  if (!icon) throw new Error(`Icon not found: ${name}`);
  const paths = [...icon.body.matchAll(/\sd="([^"]+)"/g)].map((match) => match[1]);
  if (paths.length === 0) throw new Error(`No path data in: ${name}`);
  lines.push(`  '${name}': '${paths.join(' ')}',`);
}

const output = `// Generated by scripts/build-glyphs.mjs. Do not edit by hand.
// Icons from game-icons.net by Lorc, Delapouite and contributors,
// licensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/
// Every glyph is a single path in a 512 × 512 box.

export const GLYPHS = {
${lines.join('\n')}
} as const;

export type GlyphName = keyof typeof GLYPHS;
`;

writeFileSync(new URL('../src/ui/art/glyphs.ts', import.meta.url), output);
console.log(`Wrote ${NAMES.length} glyphs.`);
